#-------------------------------
# General Site Settings
title: Prashant Kumar
logo: logo.svg # You can add own logo.
description: 


#-------------------------------
# Author Settings
author:
  name: Prashant Kumar
  image: 01.jpg
  say-hello: Hello, I’m <strong>Prashant Kumar</strong>
  bio: <strong>Quality Enthusiast,Blogger,Experimental Chef and Digital Nomad</strong> who worked and travelled across the US,UK,Switzerland,Germany and India. I teach people - how to accomplish quality and love to share my learnings, free resources and inspiration.


#-------------------------------
# Contact links
linkedin: https://www.linkedin.com/in/prashant-qa-kumar/
youtube: https://www.youtube.com/channel/UC1aDirS5iWYQpsbAEx7rFJw
medium: https://prashant-kumar.medium.com/

#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
